# -*- coding: utf-8 -*-
"""BaixarJ00a99.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t2g5neXcgtL_3Sb8Pl3F0U2ms907r39E
"""

# Remover a versão atual
!pip uninstall -y pysus

# Instalar a última versão da API clássica
!pip install pysus==0.15.0

# Instala a versão atualizada do Pysys - se necessário - se não, use a versão 0.15.0
##!pip install git+https://github.com/AlertaDengue/PySUS.git --upgrade

# Importando as bibliotecas para análise de dados (pandas), amtplotlib (gráficos), seaborn (gráficos mais atraentes),
# numpy (trabalhar com grandes volumes de dados matematicamente)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Importando a biblioteca Pysus (trabalhar com dados do Sus)
import pysus

print("Versão do PySUS:", getattr(pysus, "__version__", "versão não informada"))
print("\nConteúdo de pysus:")
print(dir(pysus))

# Importando módulo pkgutil para ler dados, e importar;
# Para descobrir quais módulos estão disponíveis em um diretório ou caminho específico, usa-se o iter_modules
import pkgutil

mods = sorted([m.name for m in pkgutil.iter_modules(pysus.__path__)])
print(mods)

print("Versão:", pysus.__version__)

print("\nSubmódulos disponíveis:")
for m in pkgutil.iter_modules(pysus.__path__):
    print(m.name)

import pysus.data as data

print(dir(data))

from pysus import CNES, SIM, SINAN, SIH, SIA, SINASC

print("PySUS clássico carregado com sucesso!")

# Teste 1
try:
    from pysus import SIH
    print("✅ from pysus import SIH")
except Exception as e:
    print("❌", e)

# Teste 2
try:
    from pysus.online_data import SIH
    print("✅ from pysus.online_data import SIH")
except Exception as e:
    print("❌", e)

# Teste 3
try:
    from pysus.ftp.databases.sih import SIH
    print("✅ from pysus.ftp.databases.sih import SIH")
except Exception as e:
    print("❌", e)

from pysus import SIH

# Carregar o SIH deu certo
sih = SIH().load()

print("Grupos disponíveis:")
print(sih.groups)

# Selecionar os 12 arquivos RD de 2004 para o estado de São Paulo
files = sih.get_files(
    "RD",
    uf="SP",
    year=2004,
    month=list(range(1, 13))
)

print(f"\nArquivos encontrados: {len(files)}")
print(files)

# Download do arquivo internações
downloaded_file = sih.download(files[0])

print("Arquivo baixado em:")
print(downloaded_file)

# Conversão para DataFrame
df = downloaded_file.to_dataframe()

print(f"\nNúmero de registros: {len(df):,}")
print(f"Número de colunas: {len(df.columns)}")

# Visualizar as primeiras linhas
df.head()

# O DataFrame 'df' já foi carregado na célula anterior

print("Colunas disponíveis:")
print(df.columns.tolist())
print("\nTipos de dados das colunas:")
print(df.dtypes)

# Exibir uma amostra dos dados
print("\n=== Primeiras linhas ===")
display(df.head())

list(df.columns)

# Exibe todas as colunas e linhas
##pd.set_option('display.max_columns', None)
##pd.set_option('display.max_rows', None)

# Exiba o seu dataframe normalmente
##print(df)

# Conversão para DataFrame
#df = downloaded_file.to_dataframe()

# Verificar o formato do código do município
print(df["MUNIC_RES"].head(20))

print("\nTamanho dos códigos:")
print(df["MUNIC_RES"].str.len().value_counts())

print("\nAlguns códigos distintos:")
display(df["MUNIC_RES"].drop_duplicates().sort_values().head(30))

# Filtrar doenças respiratórias (CID-10 J00 a J99); na=not available

df_resp = df[
    df["DIAG_PRINC"].str.startswith("J", na=False)
].copy()

print(f"Internações por doenças respiratórias: {len(df_resp):,}")

display(df_resp[
    ["DIAG_PRINC", "MUNIC_RES", "DT_INTER", "IDADE", "SEXO"]
].head())

#Como MUNIC_RES é do tipo string[python], mantenha a comparação com uma string ("355030"), e não com um número inteiro.

df_sp = df[df["MUNIC_RES"] == "355030"].copy()

print(f"Internações de residentes em São Paulo: {len(df_sp):,}")

print("Primeiros CIDs encontrados:")
print(df_resp["DIAG_PRINC"].value_counts().head(20))

UF = "SP"
ANO = 2004
MES = 1          # ou list(range(1, 13))
MUNICIPIO = "355030"
CID_INICIAL = "J"

# 1. Base completa do mês
df.to_csv(
    "SIH_RD_SP_2004_01.csv",
    index=False,
    encoding="utf-8-sig"
)

# 2. Apenas residentes no município de São Paulo
df_sp.to_csv(
    "SIH_RD_SP_Municipio_2004_01.csv",
    index=False,
    encoding="utf-8-sig"
)

# 3. Apenas doenças respiratórias (J00–J99)
df_resp.to_csv(
    "SIH_RD_SP_2004_Doencas_Respiratorias.csv",
    index=False,
    encoding="utf-8-sig"
)

# carrega o módulo OS para poder carregar, navegar em pastas e baixar arquivos no computador
import os

print("Diretório atual:")
print(os.getcwd())

print("\nArquivos no diretório:")
print(os.listdir())

# lista e atribui as colunas que queremos selecionar para baixar
COLUNAS_EXPORTACAO = [
    "MUNIC_RES",
    "IDADE",
    "SEXO",
    "CEP",
    "DT_INTER",
    "DT_SAIDA",
    "DIAG_PRINC",
    "DIAG_SECUN"
]

# Seleciona somente as colunas
df_resp[COLUNAS_EXPORTACAO].to_csv(
    "SIH_RD_SP_2004_Doencas_Respiratorias.csv",
    index=False,
    encoding="utf-8-sig"
)

import pandas as pd

# Colunas que deseja exportar
colunas_exportacao = [
    "MUNIC_RES",
    "IDADE",
    "SEXO",
    "CEP",
    "DT_INTER",
    "DT_SAIDA",
    "DIAG_PRINC",
    "DIAG_SECUN"
]

# Aplicar todos os filtros de uma só vez
df_final = df.loc[
    (df["MUNIC_RES"] == "355030") &
    (df["DIAG_PRINC"].str.startswith("J", na=False)),
    colunas_exportacao
].copy()

print(f"Total de internações encontradas: {len(df_final):,}")

display(df_final.head())

# Exportar para CSV
nome_arquivo = "SIH_RD_SP_2004_01_Respiratorias_Municipio_SP2.csv"

df_final.to_csv(
    nome_arquivo,
    index=False,
    encoding="utf-8-sig"
)

print(f"\nArquivo salvo: {nome_arquivo}")

# Baixa o arquivo xls ou csv no computador. Verificar o nome correto na célula ACIMA
from google.colab import files

files.download("SIH_RD_SP_2004_01_Respiratorias_Municipio_SP2.csv")

"""### Abaixo, alguns comandos de **estatística descritiva**"""

import pandas as pd

# Conversões seguras
df_final["IDADE"] = pd.to_numeric(df_final["IDADE"], errors="coerce")
df_final["DT_INTER"] = pd.to_datetime(df_final["DT_INTER"], errors="coerce")
df_final["DT_SAIDA"] = pd.to_datetime(df_final["DT_SAIDA"], errors="coerce")

df_final.describe(include="all")

print("Número de internações:", len(df_final))

print("\nPeríodo analisado:")
print(df_final["DT_INTER"].min())
print(df_final["DT_INTER"].max())

print("\nNúmero de diagnósticos distintos:")
print(df_final["DIAG_PRINC"].nunique())

sexo = (
    df_final["SEXO"]
    .value_counts()
    .sort_index()
)

print(sexo)

plt.figure(figsize=(8,5))

plt.hist(
    df_final["IDADE"].dropna(),
    bins=30
)

plt.title("Distribuição da idade")

plt.xlabel("Idade")

plt.ylabel("Frequência")

plt.show()

mapa_sexo = {
    "1": "Masculino",
    "3": "Feminino"
}

df_final["SEXO_DESC"] = df_final["SEXO"].map(mapa_sexo)

pd.crosstab(
    df_final["DIAG_PRINC"],
    df_final["SEXO"]
)

cid_respiratorio = {
    "J18": "Pneumonia",
    "J44": "DPOC",
    "J45": "Asma",
    "J20": "Bronquite aguda",
    "J21": "Bronquiolite",
    "J15": "Pneumonia bacteriana",
    "J96": "Insuficiência respiratória"
}

df_final["DIAG_DESC"] = df_final["DIAG_PRINC"].map(cid_respiratorio)

df_final["MES"] = df_final["DT_INTER"].dt.month

mensal = (
    df_final
    .groupby("MES")
    .size()
)
mensal.plot(
    marker="o"
)

plt.title("Internações por mês")

plt.xlabel("Mês")

plt.ylabel("Número de internações")

plt.grid()

plt.show()